/*
 * ADC_prog.h
 *
 *  Created on: 1 Nov 2023
 *      Author: DELL
 */

#ifndef ADC_PRV_H_
#define ADC_PRV_H_

#define AREF    0u
#define AVCC    1u
#define INTERNAL_2560mv_VOLTAGE_REFERENCE    3u

#define EIGHT_BITS   1u
#define TEN_BITS     2u

#define ENABLED    1u
#define DISABLED   2u
#define PRESCALER_MASK 7u
#define AUTO_TRIGGER_MASK 7u
#define CHANNEL_MASK   31u
/*Select single Ended channel */


/*Select differential channel */
typedef enum
{
	ADC0_POSITIVE_DIFFERENTAIL_ENDED_ADC0_NEGATIVE_DIFFERENTAIL_ENDED_GAIN10 = 8  ,
	ADC1_POSITIVE_DIFFERENTAIL_ENDED_ADC0_NEGATIVE_DIFFERENTAIL_ENDED_GAIN10 	  ,
	ADC0_POSITIVE_DIFFERENTAIL_ENDED_ADC0_NEGATIVE_DIFFERENTAIL_ENDED_GAIN1200    ,
	ADC1_POSITIVE_DIFFERENTAIL_ENDED_ADC0_NEGATIVE_DIFFERENTAIL_ENDED_GAIN200     ,
	ADC2_POSITIVE_DIFFERENTAIL_ENDED_ADC2_NEGATIVE_DIFFERENTAIL_ENDED_GAIN10      ,
	ADC3_POSITIVE_DIFFERENTAIL_ENDED_ADC2_NEGATIVE_DIFFERENTAIL_ENDED_GAIN10      ,
	ADC2_POSITIVE_DIFFERENTAIL_ENDED_ADC2_NEGATIVE_DIFFERENTAIL_ENDED_GAIN200     ,
	ADC3_POSITIVE_DIFFERENTAIL_ENDED_ADC2_NEGATIVE_DIFFERENTAIL_ENDED_GAIN200     ,
	ADC0_POSITIVE_DIFFERENTAIL_ENDED_ADC1_NEGATIVE_DIFFERENTAIL_ENDED_NO_GAIN     ,
	ADC1_POSITIVE_DIFFERENTAIL_ENDED_ADC1_NEGATIVE_DIFFERENTAIL_ENDED_NO_GAIN     ,
	ADC2_POSITIVE_DIFFERENTAIL_ENDED_ADC1_NEGATIVE_DIFFERENTAIL_ENDED_NO_GAIN     ,
	ADC3_POSITIVE_DIFFERENTAIL_ENDED_ADC1_NEGATIVE_DIFFERENTAIL_ENDED_NO_GAIN     ,
	ADC4_POSITIVE_DIFFERENTAIL_ENDED_ADC1_NEGATIVE_DIFFERENTAIL_ENDED_NO_GAIN     ,
	ADC5_POSITIVE_DIFFERENTAIL_ENDED_ADC1_NEGATIVE_DIFFERENTAIL_ENDED_NO_GAIN     ,
	ADC6_POSITIVE_DIFFERENTAIL_ENDED_ADC1_NEGATIVE_DIFFERENTAIL_ENDED_NO_GAIN     ,
	ADC7_POSITIVE_DIFFERENTAIL_ENDED_ADC1_NEGATIVE_DIFFERENTAIL_ENDED_NO_GAIN     ,
	ADC0_POSITIVE_DIFFERENTAIL_ENDED_ADC2_NEGATIVE_DIFFERENTAIL_ENDED_NO_GAIN     ,
	ADC1_POSITIVE_DIFFERENTAIL_ENDED_ADC2_NEGATIVE_DIFFERENTAIL_ENDED_NO_GAIN     ,
	ADC2_POSITIVE_DIFFERENTAIL_ENDED_ADC2_NEGATIVE_DIFFERENTAIL_ENDED_NO_GAIN     ,
	ADC3_POSITIVE_DIFFERENTAIL_ENDED_ADC2_NEGATIVE_DIFFERENTAIL_ENDED_NO_GAIN     ,
	ADC4_POSITIVE_DIFFERENTAIL_ENDED_ADC2_NEGATIVE_DIFFERENTAIL_ENDED_NO_GAIN     ,
	ADC5_POSITIVE_DIFFERENTAIL_ENDED_ADC2_NEGATIVE_DIFFERENTAIL_ENDED_NO_GAIN     ,

}ADC_Channel_Differential_t;
/*prescaler division factors selection  */
#define ADC_PRESCALER_DIVISIO_FACTOR_BY_2      1u
#define ADC_PRESCALER_DIVISIO_FACTOR_BY_4      2u
#define ADC_PRESCALER_DIVISIO_FACTOR_BY_8      3u
#define ADC_PRESCALER_DIVISIO_FACTOR_BY_16     4u
#define ADC_PRESCALER_DIVISIO_FACTOR_BY_32     5u
#define ADC_PRESCALER_DIVISIO_FACTOR_BY_64     6u
#define ADC_PRESCALER_DIVISIO_FACTOR_BY_128    7u

/*select the source of auto trigger */
#define FREE_RUNNING_MODE                      0u
#define ANALOG_COMPARATOR                      1u
#define EXTERNAL_INTERRUPT_REQUEST_0           2u
#define TIMER_COUNTER0_COMPARE_MATCH           3u
#define TIMER_COUNTER0_OVERFLOW                4u
#define TIMER_COUNTER1_COMPARE_MATCH_B         5u
#define TIMER_COUNTER1_OVERFLOW                6u
#define TIMER_COUNTER1_CAPTURE_EVENT           7u

#endif /* ADC_PRV_H_ */
